Readme update
LBHackney-IT/documents-api pull request #101
Opened 2022-01-21 15:56 UTC by bella-cockrell

## Describe this PR

### *What is the problem we're trying to solve*

Update the README to provide new set up instructions to get envars and new commands.

### *What changes have we introduced*

The README was previously providing make instructions to get the project running that didn't work. 

#### _Checklist_

- [ ] Added end-to-end (i.e. integration) tests where necessary e.g to test complete functionality of a newly added feature
- [ ] Added tests to cover all new production code
- [ ] Added comments to the README or updated relevant documentation _(add link to documentation)_, where necessary.
- [ ] Checked all code for possible refactoring
- [ ] Code pipeline builds correctly

2022-02-16 16:58 UTC, bogdan-zaharia requested changes

2022-02-16 16:58 UTC, bogdan-zaharia commented on README.md
> +This will spin up a new container called `documents-api_test-database_1` that the integration tests use. If this is your first time running the tests, then some will fail. You will need to run a new
typo "...but running again" -> "...by running again"

2022-02-17 11:13 UTC, bella-cockrell commented on README.md
> +In order to run the API locally, you will first need access to the environment variables stored in 1Password. Please contact another developer on the Document Evidence Service Team to gain access.
Turns out that the local envars are the same as the ones in `.env.example` so I've updated the text to just say to get them from there.

2022-03-28 08:43 UTC, bogdan-zaharia approved these changes

2022-03-28 08:44 UTC, merged