Add authorization using google groups to the endpoint to get claims by target ID
LBHackney-IT/documents-api pull request #156
Opened 2022-09-21 15:11 UTC by bogdan-zaharia

## Link to JIRA ticket

https://hackney.atlassian.net/browse/DOC-1141

## Describe this PR

### *What changes have we introduced*

Added authorization using google groups to the endpoint used to get claims by target ID.

- The authorization is using the [lbh-core](https://github.com/LBHackney-IT/lbh-core) library
- Added changes to the docker files and docker-compose files to allow the usage of the lbh-core library
- Added NuGet package configuration (which is using a secret token to allow usage)
- Updated tests to contain the authorization header
- Updated the README file with information regarding setting up the new token needed to use the lbh-core library

#### _Checklist_

- [x] Added end-to-end (i.e. integration) tests where necessary e.g to test complete functionality of a newly added feature
- [x] Added tests to cover all new production code
- [x] Added comments to the README or updated relevant documentation _(add link to documentation)_, where necessary.
- [x] Checked all code for possible refactoring
- [x] Code pipeline builds correctly

2022-09-22 14:21 UTC, martapederiva commented on DocumentsApi.Tests/V1/Authorization/AuthorizeByGroupsTests.cs
> +            var incorrectEnvVariable = "var";
have you considered just using "incorrectEnvVariable" as a string directly in the function call, instead of declaring it as a variable here and then feeding it to the function? just because there's no other variables that may cause confusion and doing so would result in slightly less code.

2022-09-22 14:22 UTC, martapederiva approved these changes
Looks good to me, added a comment which is more of a curiosity and by no means blocking anything

2022-09-23 10:12 UTC, andrewclowes commented on DocumentsApi/DocumentsApi.csproj
> +    <PackageReference Include="Hackney.Core.Http" Version="1.70.0" />
Adding these via the `dotnet add package` command would keep this file organised and make things easier find.

2022-09-23 10:15 UTC, andrewclowes commented on DocumentsApi/serverless.yml
> +    ALLOWED_GOOGLE_GROUPS: /documents-api/${self:provider.stage}/get/claims/allowed-google-groups
I just realised that here we have the SSM parameter as `/get/claims/allowed-google-groups` but the env var is just `ALLOWED_GOOGLE_GROUPS`. Do you think renaming the env var to `GET_CLAIMS_ALLOWED_GOOGLE_GROUPS` would make it more explicit?

2022-09-23 10:25 UTC, bella-cockrell requested changes

2022-09-23 10:25 UTC, bella-cockrell commented on README.md
> +The values for all the env vars can be found in the Parameter Store, in `Document-Evidence-Store-Staging` and `Document-Evidence-Store-Production` AWS accounts.
Would you be able to add which env var it is in SSM?

2022-09-23 10:48 UTC, bogdan-zaharia commented on DocumentsApi.Tests/V1/Authorization/AuthorizeByGroupsTests.cs
> +            var incorrectEnvVariable = "var";
Agree with Bella, I think it helps with readability

2022-09-23 11:12 UTC, bogdan-zaharia commented on README.md
> +The values for all the env vars can be found in the Parameter Store, in `Document-Evidence-Store-Staging` and `Document-Evidence-Store-Production` AWS accounts.
This is just a general guidance for all of the env vars, not specific ones.

2022-09-23 11:35 UTC, bogdan-zaharia commented on DocumentsApi/DocumentsApi.csproj
> +    <PackageReference Include="Hackney.Core.Http" Version="1.70.0" />
addressed

2022-09-23 11:35 UTC, bogdan-zaharia commented on DocumentsApi/serverless.yml
> +    ALLOWED_GOOGLE_GROUPS: /documents-api/${self:provider.stage}/get/claims/allowed-google-groups
addressed

2022-09-23 11:35 UTC, bogdan-zaharia commented on README.md
> +You will also need to seprately set up `LBHPACKAGESTOKEN` env var (used to access the [lbh-core](https://github.com/LBHackney-IT/lbh-core) library) in your terminal profile or in every terminal windo
addressed

2022-09-23 11:35 UTC, bogdan-zaharia commented on .env.example
> +LBHPACKAGESTOKEN=token
addressed

2022-09-23 11:36 UTC, bogdan-zaharia commented on DocumentsApi.Tests/V1/Authorization/AuthorizeByGroupsTests.cs
> +        public void ConstructorThrowsErrorIfGroupsEnvVariableIsNull()
addressed

2022-09-23 11:36 UTC, bogdan-zaharia commented on DocumentsApi.Tests/V1/Authorization/AuthorizeByGroupsTests.cs
> +        private (AuthorizationFilterContext, HeaderDictionary) SetUpMockContextAndHeaders()
addressed

2022-09-23 11:38 UTC, bogdan-zaharia commented on DocumentsApi.Tests/V1/E2ETests/ClaimsTest.cs
> +            Client.DefaultRequestHeaders.Add("Authorization", TestToken.Value);
addressed

2022-09-23 11:48 UTC, bogdan-zaharia commented on DocumentsApi.Tests/V1/Authorization/AuthorizeByGroupsTests.cs
> +            (context.Result as UnauthorizedObjectResult).Value.Should().Be("User  is not authorized to access this endpoint.");
addressed

2022-09-23 11:48 UTC, bogdan-zaharia commented on DocumentsApi/V1/Authorization/AuthorizeByGroups.cs
> +                context.Result = new UnauthorizedObjectResult($"User {token?.Name} is not authorized to access this endpoint.");
addressed

2022-09-23 11:57 UTC, andrewclowes approved these changes

2022-09-23 12:03 UTC, andrewclowes commented on DocumentsApi/V1/Authorization/AuthorizeByGroups.cs
> +                context.Result = new UnauthorizedObjectResult($"User {token?.Name} is not authorized to access this endpoint.");
In our case, a `null` token would never reach our API due to our API sitting behind the Lambda authoriser. If the Lambda Authoriser has done its job for the user auth flow then there will certainly be a token that contains Google Group names.

2022-09-23 13:06 UTC, bella-cockrell approved these changes

2022-09-23 13:07 UTC, bella-cockrell commented on DocumentsApi/V1/Authorization/AuthorizeByGroups.cs
> +                context.Result = new UnauthorizedObjectResult($"User {token?.Name} is not authorized to access this endpoint.");
Ah I see, so a 401 would be caught at the Lambda level, not here?

2022-09-23 13:18 UTC, andrewclowes commented on DocumentsApi/V1/Authorization/AuthorizeByGroups.cs
> +                context.Result = new UnauthorizedObjectResult($"User {token?.Name} is not authorized to access this endpoint.");
The Lambda Authoriser should handle the case where there are issues with the token, as seen [here](https://github.com/LBHackney-IT/api-auth-verify-token/blob/master/ApiAuthVerifyToken/V1/UseCase/VerifyAccessUseCase.cs#L50).

2022-09-23 13:28 UTC, merged